### ISSUE TITLE
Plugin doesn't work in PhpStorm 2018.2 EAP

### ISSUE THREAD

**Issue by toxicdog** [chocotan/webbrowser4idea#1]
PhpStorm 2018.2 EAP
Build #PS-182.2371.32, built on May 17, 2018
JRE: 1.8.0_152-release-1226-b7 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

`org/apache/commons/lang3/StringUtils
java.lang.NoClassDefFoundError: org/apache/commons/lang3/StringUtils
  at io.loli.browserfx.Browser.lambda$initWebView$4(Browser.java:105)`

**Comment by vistarsvo** [comment]
Yes. It's true. Doesn't work :(

PhpStorm 2018.1.4
Build #PS-181.5087.24, built on May 18, 2018
JRE: 1.8.0_152-release-1136-b39 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-22-generic
org/apache/commons/lang3/StringUtils
java.lang.NoClassDefFoundError: org/apache/commons/lang3/StringUtils
	at io.loli.browserfx.Browser.lambda$initWebView$4(Browser.java:105)
	at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$5(GtkApplication.java:139)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang3.StringUtils PluginClassLoader[io.loli.browserfx, 1.1.2] com.intellij.ide.plugins.cl.PluginClassLoader@4737a582
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:63)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 8 more

**Comment by chocotan** [comment]
Thanks for your feedback.
Please try this version i uploaded, it may works now.
[browserfx.tar.gz](https://github.com/chocotan/webbrowser4idea/files/2041602/browserfx.tar.gz)


I used JavaFX WebView to load HTML into the scene, it is unstable and may cause IDEA to crash  : (
